development:
  adapter: postgresql
  database: development
  pool: 5
  timeout: 5000
  username: postgres
  password: jordan

test:
  adapter: postgresql
  database: test
  pool: 5
  timeout: 5000
  username: postgres
  password: jordan

production:
  adapter: postgresql
  database: db
  pool: 5
  timeout: 5000
  username: postgres
  password: jordan

